### PR TITLE
Updated build scripts to use non-core version of CAKE

### PR DESCRIPTION
**Pull request by thecodejunkie**
Making some preparations to enable us to support `netstandard2`

## Planned changes
- [x] Update `.travis.yml` to build using `dotnet 1.1.4`
- [x] Update `build.ps1` to use the non-core version of CAKE and `0.24.0`
- [x] Update `build.sh` to use the non-core version of CAKE and `0.24.0`

### CODE REVIEW

**Comment by thecodejunkie** [comment]
@khellang this seems to work. Should be merged with the changes you've made to `build.*` in #2848

**Comment by thecodejunkie** [comment]
@NancyFx/most-valued-minions 👀

**Comment by khellang** [comment]
When you're touching this file anyway, could you add OSX as well?

**Comment by thecodejunkie** [comment]
@khellang sure. The one thing I did notice (I accidentally had it as osx-only first) is that OSX builds are queued for quite some time on Travis (at least the night when I tried it). I'll had it back in and we can see how it affects out CI build times

**Comment by thecodejunkie** [comment]
@khellang added OSX

**Comment by thecodejunkie** [comment]
https://travis-ci.org/NancyFx/Nancy/jobs/326108056#L2813

Maybe we should add OSX stuff as a separate PR

**Comment by thecodejunkie** [comment]
@khellang OK this now builds on an OSX agent as well 😄

**Comment by khellang** [comment]
OK, time to rebase #2848 on this 👍

**Pull request merged**
