### PR TITLE
Update to Netstandard2.0 + xUnit 2.4 beta

### PR DESCRIPTION
**Pull request by blairconrad**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that **there is an open overlapping pull request - #2848**
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)

### Description

Builds upon @khellang's work. Closes #2848.

### CODE REVIEW

**Comment by thecodejunkie** [comment]
@blairconrad @khellang this is awesome! So the failing AppVeyor tests are real failures I think. I believe they changes the behavior of `Path.GetFullPath` maybe extract those calls into their own `SafeGetFullPath` and capture the exception?

**Comment by blairconrad** [comment]
Thanks, @thecodejunkie. I'd suspected real failures too but had, well, forgotten about this PR. 😊 
Anyhow, I took a stab at your suggestion, just bailing early when there was an error, and making up some trace output. If you're happy with the general direction, I'm more than content to make any changes you'd like.
(And then there's the issue of squashing and whatnot. I don't know Team Nancy's policy on tidying branches, but I guess the transition through .NET SDK 2.1.3 to 2.1.4 may not be desirable. If you or @khellang'd rather just take my commits and merge with @khellang's and shape into a more palatable form, that's fine too!)

**Comment by thecodejunkie** [comment]
Sweet @blairconrad happy to merge this

@khellang care to take a 👀 before we merge it?

❤️

**Comment by khellang** [comment]
I think this looks good! ❤️

**Comment by blairconrad** [comment]
Thanks, @khellang and @thecodejunkie!

**Pull request merged**
