### PR TITLE
Merge coreclr branch into master (attempt 2)

### PR DESCRIPTION
**Pull request by thecodejunkie**
:scream: 

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [X] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [X] I have provided test coverage for my change (where applicable)

### Description
Let's try this again, without @grumpydev being massive :trollface: and closing the pull-request :smile:

### CODE REVIEW

**Comment by grumpydev** [comment]
Moi? 😀

**Comment by Yantrio** [comment]
I'm not too sure about this, how do you feel about multiple things going into a single PR @grumpydev ? :trollface:

**Comment by jchannon** [comment]
De ja vu



WOO

PARTY

**Comment by jchannon** [comment]
MERGED!!

**Comment by jchannon** [comment]
So excited.....

**Comment by chriscamplejohn** [comment]
Well done guys!!!

**Comment by thecodejunkie** [comment]
Well done! There's been much learning and much frustration involved to make this happen

**Comment by jchannon** [comment]
Thanks to all involved!

**Comment by thecodejunkie** [comment]
We need to get @jeremymeng and @davidfowl in here as well :P

**Comment by Yantrio** [comment]
Also, Woo I'm finally on the contributors list 😄

**Comment by mike-ward** [comment]
giphy

**Comment by jeremymeng** [comment]
Awesome! 🏆

**Comment by davidfowl** [comment]
👏

**Comment by phillip-haydon** [comment]
Splooge

**Pull request merged**
