### PR TITLE
Body populated with error when XML/JSON serialization takes place

### PR DESCRIPTION
**Pull request by jchannon**
I had a cyclical POCO reference that was marked with XmlIgnore attributes and when a request came in and I used application/xml this returned my data however when using application/json I got a blank response.

This puts a try/catch around the call to Serialize and writes the exception message to the stream.

### CODE REVIEW

**Comment by thecodejunkie** [comment]
@jchannon should we revive this or close it?

**Comment by jchannon** [comment]
Revive? I must have worked around it but still seems a valid issue?

**Comment by thecodejunkie** [comment]
Alright

> Nope, was after some help

What kind of help were you looking for? Should we target this for the 1.3 or 1.4 timeframe?

**Comment by phillip-haydon** [comment]
@jchannon why do you break everything!

**Comment by jchannon** [comment]
We can try 1.3. I think I was after some help as in someone else clone and
try on their machine to see if they see the same

@philliphaydon just pushing the limits :p

**Comment by thecodejunkie** [comment]
@jchannon what can I do to help bring this ship into port?

**Comment by jchannon** [comment]
Clone it and see if you see the debug vs release issue I guess

**Comment by ClemPi** [comment]
Hi.

I'm not sure silently catching the exception is a good practice. It will lead to a request returning 200 OK with empty content when the serialization fail.

**Comment by jchannon** [comment]
This is a PR that wasn't merged

**Comment by ClemPi** [comment]
Yes, but #2086 was merged.

**Comment by jchannon** [comment]
#2086 looks the one you want. Take a look at that and then append the tests to check the response status code and see what they say. If not correct feel free to send a PR :)

**Pull request closed without merging**
