### PR TITLE
Added IncludeInNancyAssemblyScanningAttribute

### LINKED ISSUE #1842: Using an assembly reference to improve accuracy of assembly loading
During assembly scanning, we try to work a bit of magic by scanning for unloaded assemblies that reference as Nancy assembly. However, as we know, .NET is sometimes trying to be smart and clear referenced assemblies, where a type is not directly referenced in code. This results in Nancy not loading the assembly thus some types will not be loaded and be discovered by Nancy at runtime. There is little we can do about this behavior (unless, explicitly force people to add a type reference somewhere in their code).

One possible workaround could be to look for an attribute (guessing that they'll not be cleaned up)

```c#
[AttributeUsage(AttributeTargets.Assembly)]
public class NancyReferenceAttribute : Attribute
{
}
```

It could then be slapped on an assembly

`[assembly: NancyReference]`

We could then update ADATS to look for the attribute first and if it's not present, then we will try and look for a Nancy reference. Come to think of it, the attribute usage should be considered a directer type usage so it's mimicking referencing a Nancy type, in a less convoluted approach. We shouldn't need to update ADATS, the attribute would just provide (in my opinion) a cleaner approach to the solution we tell people to use.

Thoughts?

### PR DESCRIPTION
**Pull request by khellang**
This adds the `IncludeInNancyAssemblyScanningAttribute`. Let's do a final round on the name. Does anyone care much? :smile:

I also tried to make ADATS look for the attribute before checking an assembly's references, but failed to get it to work in reflection-only context :disappointed: 

Closes #1842

### CODE REVIEW

**Comment by thecodejunkie** [comment]
I think the name is alright. What say the @NancyFx/most-valued-minions @NancyFx/nancy-core-contributors ?

**Comment by grumpydev** [comment]
:shipit:

**Comment by jchannon** [comment]
Does it fix #1629?

**Comment by horsdal** [comment]
Only if the other libraries add the new attribute.

And :+1: for the name (no surpise :smile: )

**Comment by thecodejunkie** [comment]
Yeah it **should** fix it. The theory is that if you slap this on your assembly, then .net can't try and be smart and remove the Nancy reference if you don't directly use a type.

**Comment by jchannon** [comment]
It's not always Nancy needed it's things like the validation lib

**Comment by khellang** [comment]
Updated the wiki with a note on this attribute: https://github.com/NancyFx/Nancy/wiki/Bootstrapper#finding-the-right-bootstrapper

**Pull request merged**
