### PR TITLE
upgrade FakeItEasy and FakeItEasy.Analyzer to 2.2.0

### PR DESCRIPTION
**Pull request by adamralph**
### Prerequisites
- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)
### Description

As it says on the tin.

### CODE REVIEW

**Comment by thecodejunkie** [comment]
@adamralph there is a pre-release version now, of FIE, that support core correct? Maybe we should look into using that and get our tests back up on core

**Comment by adamralph** [comment]
@thecodejunkie not quite yet. You *can* grab it from TeamCity, but that feed isn't reliable. We can and should get a proper pre-release up fairly soon though.

**Comment by thecodejunkie** [comment]
@adamralph cheers for the update.. looking forward to the pre-release! :D

**Comment by jchannon** [comment]
Any ETA?

**Comment by adamralph** [comment]
Not yet.

Personally I'm fairly busy this week but I'll try and catch up with the rest of the FIE guys next week. We should be able to push out a beta to myget fairly soon.

**Comment by thecodejunkie** [comment]
@blairconrad I think with your porting work, this one can be closed right?

**Comment by blairconrad** [comment]
I didn't even know this existed. Yes. Superseded by my work.

**Comment by thecodejunkie** [comment]
Thanks Adam!

**Pull request closed without merging**
