### PR TITLE
Catch exception in Middleware ans set 500 and write exception message

### PR DESCRIPTION
**Pull request by jchannon**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [ ] I have provided test coverage for my change (where applicable)

### Description
Addresses #1594

### CODE REVIEW

**Comment by jchannon** [comment]
The try catch can go where it is in this PR or we can go a bit further in and try/catch `handler.Handle` in the engine CheckStatusCodeHandler method. You decide 😄

**Comment by psibernetic** [comment]
I vote to move the try catch to CheckStatusCodeHandler in NancyEngine. 

That way all hosts benefit from this change, I don't even know what would happen in a non-nancy host, just fail to respond I guess?

**Comment by jchannon** [comment]
No still would work. I use OwinHttpListener host and that eventually sets the 500 even though the environment says its 200 in MW.

Putting the try/catch in the CheckStatusCodeHandler would solve the issue at hand but I wonder if the try/catch at a higher level might catch other issues not thought of yet

**Comment by jchannon** [comment]
Looks like TeamCity doesnt like the await in the catch block. Guess appveyor and travis use a C#6 compiler? What to do?

**Comment by khellang** [comment]
> I don't even know what would happen in a non-nancy host, just fail to respond I guess?

For ASP.NET/IIS, it'd return the YSOD 😁

**Comment by khellang** [comment]
> ooks like TeamCity doesnt like the await in the catch block. Guess appveyor and travis use a C#6 compiler? What to do?

Yeah, we desperately need to get the newer build bits on that build machine. Don't you guys work full time on this? :wink:

**Comment by jchannon** [comment]
Its because @thecodejunkie watches cat videos all day

**Comment by jchannon** [comment]
Closed in favour of #2457

**Pull request closed without merging**
