### PR TITLE
Added Netstandard support to Nancy.ViewEngines.Markdown

### PR DESCRIPTION
**Pull request by Sphiecoh**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [ ] I have provided test coverage for my change (where applicable)

### Description

 Use [Markdown](https://www.nuget.org/packages/Markdown) package which supports netstandard and is actively mantained.

### CODE REVIEW

**Comment by horsdal** [comment]
I reran the build. Still fails. Could you take a look, @Sphiecoh ?

**Comment by Sphiecoh** [comment]
will rebase this weekend and see

On Thu, Mar 9, 2017 at 12:25 AM, Christian Horsdal <notifications@github.com

**Comment by thecodejunkie** [comment]
Re-ran the tests and made them pass ;) Needs rebasing though

**Comment by thecodejunkie** [comment]
@Sphiecoh I think we both can agree that this re-base was less than successful 😮 Please let us know if you need any help resolving it. This issue https://github.com/NancyFx/Nancy/pull/2697#issuecomment-284184051 has a similar problem and I detailed steps to take

**Comment by Sphiecoh** [comment]
This is what I have done:

1. git reset 
2. git merge --no-commit master
3. fixed the conflict
4. git commit 

Now I think am ready to push with `-f`

**Comment by thecodejunkie** [comment]
@Sphiecoh not exactly how I would've solved it (I would have used the approach I linked to), so it is impossible for me to say what you commits will look like. Git a the swiss army knife of VCS, so your approach might as well be as reliable as mine 😄 push it and see what it looks like

**Comment by thecodejunkie** [comment]
Any luck?

**Comment by Sphiecoh** [comment]
I would say it was success 👍

**Comment by horsdal** [comment]
LGTM 👍

**Pull request merged**
