### PR TITLE
Check that the body deserializer stream is Seekable before doing so

### PR DESCRIPTION
**Pull request by vbfox**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [ ] I have provided test coverage for my change (where applicable)

### Description

Code unification with other serializers, see https://github.com/NancyFx/Nancy.Serialization.JsonNet/pull/38 for more details.

(No tests on this specific detail for now, and I don't know if this repo had tests on the position reset behavior, can add them if needed)

### CODE REVIEW

**Comment by khellang** [comment]
Thanks @vbfox! :heart:

**Comment by jeff-pang** [comment]
Confirmed that this pull request causes Travis to fail test at Nancy.Testing.Tests.BrowserFixture.Should_return_JSON_serialized_form. I have raised this in issue #2509

**Comment by jchannon** [comment]
How did this cause the serialize form test to fail?

**Comment by phillip-haydon** [comment]
Looks like a false positive.

**Comment by jeff-pang** [comment]
The failed build here https://travis-ci.org/NancyFx/Nancy/builds/145179515
Subsequently I undid the implementation here and it succeeded here https://travis-ci.org/NancyFx/Nancy/builds/145180948

I am not exactly clear why this caused serialised form test to fail, however it has something to do with serialising the string "1" to integer.

**Comment by jchannon** [comment]
If you debug it and look at the stream before it does the model binding
what is the string vaue?

**Comment by jeff-pang** [comment]
@jchannon The test passed on my machine and also succeeded on AppVeyor. The test only fails on TravisCI, hence I am unable to debug it.

**Comment by jchannon** [comment]
Aye its a weird one thats been effecting most of our PRs :(

**Comment by jeff-pang** [comment]
@jchannon it could be difference in behaviour for Linux + Mono builds, but unfortunately I don't have Linux environment to test this out.

**Pull request merged**
