### PR TITLE
I18N to SuperSimpleViewEngine (Added a GetDynamicMember Method in the SuperSimpleViewEngine)

### PR DESCRIPTION
**Pull request by jjchiw**
From https://github.com/NancyFx/Nancy/pull/1586 only with the real file modified and without the DemoProject

### CODE REVIEW

**Comment by jjchiw** [comment]
Can you merge this, please...

**Comment by khellang** [comment]
@jjchiw Would you mind rebasing this and squashing the commits? There's quite a lot of "oh shit"-commits in there :wink:

**Comment by horsdal** [comment]
and maybe remove the extra spaces in front of parenthesis.

**Comment by jjchiw** [comment]
@khellang Ok, I think it's done, yay!  :)

**Comment by khellang** [comment]
Landed in 8dfb115869d6369c86a968deb8ce1ac0e4854b68. Fixed the extra spaces that @horsdal was talking about :smile:

**Pull request closed without merging**
