### PR TITLE
project.json upgrades for .net standard 1.6 and RTM versions

### PR DESCRIPTION
**Pull request by cemremengu**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)

### Description
Upgrades for netstandard1.6

### CODE REVIEW

**Comment by annymsMthd** [comment]
Package Nancy 2.0.0-Pre1758 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Nancy 2.0.0-Pre1758 supports: net45 (.NETFramework,Version=v4.5)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Not sure if this is the right spot to post this but it looks like this PR was trying to get support for RTM working. I found the build that got pushed to myget and it is still saying this on "dotnet restore"

**Comment by jchannon** [comment]
This PR isn't on myget

Ping @thecodejunkie

**Comment by annymsMthd** [comment]
It looks like it here http://nancy-ci.cloudapp.net/viewLog.html?buildId=7350&buildTypeId=Nancy_NancyMaster&tab=buildChangesDiv

I don't know much about the NancyCI so I could be wrong though

**Comment by annymsMthd** [comment]
I think I see it now. http://nancy-ci.cloudapp.net/viewLog.html?buildId=7350&buildTypeId=Nancy_NancyMaster&tab=buildLog#_state=10599,10601,33,9135,10568,10574,9152,10082&focus=10112

Looks like only .net45 is being packed in the nuget library folder. I'll keep investigating and see if I can come up with a fix. It also looks like alot of .cs files are being packed in there too I'm not sure if that is intentional or not

**Pull request merged**
