### PR TITLE
Nancy razor now handles code helpers in the App_Code directory

### PR DESCRIPTION
**Pull request by lukesmith**
This is a stab at getting the Nancy Razor view engine to render `@helper`s that are present in the `App_Code` directory, which can be [used across multiple views](http://weblogs.asp.net/scottgu/archive/2011/05/12/asp-net-mvc-3-and-the-helper-syntax-within-razor.aspx).

The main changes to nancy were
- extracting the `NancyRazorEngineHostFactory` which creates either the `NancyRazorEngineHost` or the new `NancyRazorCodeEngineHost` depending on whether the view location is in `App_Code` or not.
- Adding `NancyRazorCodeBase` as the base class for the app_code helpers (extracted shared methods from `NancyRazorViewBase` into `NancyPageBuilder`).

The build providers need to be referenced in the web.config In order to get the `@helper` files compiled.

The `@helper` methods compile to static methods so I couldn't see a way to expose access to the `Model` and `HtmlHelper` instances. For reference the generated class

```
Line 12:   namespace RazorOutput {
Line 13:       
Line 14:       
Line 15:       public class CodeHelper : Nancy.ViewEngines.Razor.NancyRazorCodeBase {
Line 16:           
Line 17:   #line hidden
Line 18:   
Line 19:   #line default
Line 20:   #line hidden
Line 21:   public static Nancy.ViewEngines.Razor.HelperResult Render(string text)
Line 22:   {
Line 23:   #line default
Line 24:   #line hidden
Line 25:   return new Nancy.ViewEngines.Razor.HelperResult(__razor_helper_writer => {
Line 26:    
Line 27:   
Line 28:   WriteLiteralTo(__razor_helper_writer, "    <p>");
Line 29:   
Line 30:   WriteTo(__razor_helper_writer, text);
Line 31:   
Line 32:   WriteLiteralTo(__razor_helper_writer, "</p>\r\n");
Line 33:   
Line 34:   
Line 35:   });
Line 36:   
Line 37:   #line default
Line 38:   #line hidden
Line 39:   }
Line 40:   #line default
Line 41:   #line hidden
Line 42:   
Line 43:           
Line 44:           public CodeHelper() {
Line 45:           }
Line 46:       }
Line 47:   }
Line 48:   
```

### CODE REVIEW

**Comment by billypon** [comment]
When will these commits be merged? It's useful, I need it!

**Comment by thecodejunkie** [comment]
Needs rebasing and my question answered =)
Should be able to get it into v1.3 or v1.4 depending on timeframe and review help from @NancyFx/most-valued-minions  :D

**Comment by billypon** [comment]
OK, I'm looking forward to the new version :)

**Comment by thecodejunkie** [comment]
@lukesmith Hi.. seem my review comments? Thanks =)

**Comment by phillip-haydon** [comment]
@thecodejunkie if we don't get a reply by the weekend I'll send a new PR for this and get it out of the way.

**Comment by thecodejunkie** [comment]
:+1:

**Comment by lukesmith** [comment]
Hey sorry. I'm not going to have the time to pick this up, so it would be great if @phillip-haydon could continue with it.

**Comment by khellang** [comment]
Closing this in favor of #2028

**Pull request closed without merging**
