### PR TITLE
Made AsyncUsageAnalyzers a build dependency

### PR DESCRIPTION
**Pull request by jchannon**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)

### Description
Addresses first item in TODO list #2659

### CODE REVIEW

**Comment by thecodejunkie** [comment]
Did you also verify that all `packages.config` are properly setup as well?

**Comment by thecodejunkie** [comment]
ping @NancyFx/most-valued-minions @NancyFx/owners are we OK with the json re-formatting of this PR?

**Comment by phillip-haydon** [comment]
Makes it easier to read for me... I'm impartial tho.

**Comment by jchannon** [comment]
I fixed it then when i saved, formatted it, then i thought hmm that formatting is broken so I took our original json and put it into 3 or 4 different json prettifiers and they all produced the same as what my PR did so I’m going to argue our formatting is wrong 😄 

Will check the packages.config

**Comment by jchannon** [comment]
Yup they already seem to be marked as build only

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AsyncUsageAnalyzers" version="1.0.0-alpha003"
targetFramework="net45" developmentDependency="true" />
</packages>

**Pull request merged**
