### PR TITLE
Port production projects to project.json

### PR DESCRIPTION
**Pull request by khellang**
This PR will port all "production" projects to project.json, side by side with the old .csprojs, compiling for net45 and dnx451 :sparkles:

Next step is to get the demo- and test projects over, then port everything to `dotnet5.3`. Once everything is ported and runs, we can finally kill all the .csprojs, and hopefully most of the ruby stuff as well.

The PR builds on top of #2154.

### CODE REVIEW

**Comment by jchannon** [comment]
LGTM

**Comment by horsdal** [comment]
Only looked at the last commit. :+1: for that.
Also agree that the step you wrote in the PR description are a good path to get to core.

**Comment by horsdal** [comment]
Also quite like the restructuring. Especially getting the samples into their own folder.

**Comment by phillip-haydon** [comment]
Looks good to me. I just hope prior to V2 release we can ditch the csproj files.

**Comment by khellang** [comment]
I can't bother keeping this up to date if it's being held off until 3.0 anyway...

**Pull request closed without merging**
