### PR TITLE
Add support for deserializing to nullable number types

### LINKED ISSUE #2529: SimpleJson doesn't support nullable integers
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
### Description

If the class you're deserializing to has a nullable integer then SimpleJson throws an exception.
### Steps to Reproduce

I just ran into this issue last week in my own project and had to hack around it. Modifying the tests in [BrowserFixture.cs](https://github.com/NancyFx/Nancy/blob/d76e7ef6ee938c8ac1f3c42b50b610c158fdeccc/test/Nancy.Testing.Tests/BrowserFixture.cs) so the test model's `int` is `int?` exposes the issue here as well.

I can put together a PR for this in the next day or so. I just wanted to report this before I forgot about it.

### PR DESCRIPTION
**Pull request by xt0rted**
### Prerequisites
- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)
### Description

Adds support for deserializing to nullable number types as well as numeric strings.

With this update `42` and `"42"` will both deserialize to `int?`

Fixes #2529

### CODE REVIEW

**Comment by jchannon** [comment]
Looking at what you changed, this implies that all nullable types might not be deserializeable is that correct?

**Comment by khellang** [comment]
Ideally we shouldn't make changes to that file. Changeso should be made upstream and brought down with NuGet. I'm not sure how active the SimpleJson repo is though. I'm just afraid we'llblgen regress this if we ever pull a new version without the changes applies upstream.

**Comment by jchannon** [comment]
We already have differences in the file and I think SimpleJson isn't very
active

**Comment by xt0rted** [comment]
As @prabirshrestha has said this project isn't really maintained at this point (it's been [over 2 years](https://github.com/facebook-csharp-sdk/simple-json/commits/master) since their last commit). The Nancy team was offered commit access to the repo so maybe we can move forward with that and then move all these changes upstream? If not we should at least pull in all of the unit tests to ensure we don't break anything with the changes we're making now.

**Comment by thecodejunkie** [comment]
@xt0rted @jchannon @khellang could you guys revive this and see about getting it in? Let's live with the fact that we'll diverge from upstream SimpleJson for the time being (I personally do not see us owning that project for many reasons - time and lack of understanding of the code base, being the two major ones). Since it's not actively maintained anymore, we cannot be blocked by it

@xt0rted can always send a PR to the SimpleJson repo and @prabirshrestha can decide if we want's to pull it in or not

My 2 cents 😄

**Comment by xt0rted** [comment]
Rebased and waiting review.

**Comment by thecodejunkie** [comment]
@khellang ?

**Comment by khellang** [comment]
LGTM! Thanks ❤️

**Comment by thecodejunkie** [comment]
Thanks guys!

**Pull request merged**
