### PR TITLE
Fix bootstrapper resolution error

### LINKED ISSUE #2617: Nancy.Bootstrapper.BootstrapperException: Located multiple bootstrappers
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed]  issues to ensure it has not already been reported

### Description

When you implement a bootstrapper other then the default one, nancy fails to starts unless
you explicitly specify your bootstrapper with

```
app.UseOwin(x => x.UseNancy(options => { options.Bootstrapper = new Bootstrapper(); }));
```

Let me know if you need a sample project showing this (I couldnt attach here)

### Steps to Reproduce
- Get the packages
- Create a bootstrapper by implementing the AutofacBootstrapper. (so that there is only one bootstrapper that is explicitly implemented)
- Run your app wıth `app.UseOwin(x => x.UseNancy());`
- Bon apetit!

```
namespace BootstrapperBug
{
    using Autofac;
    using Nancy;
    using Nancy.Bootstrapper;
    using Nancy.Bootstrappers.Autofac;

    public class Bootstrapper : AutofacNancyBootstrapper
    {
        protected override void ApplicationStartup(ILifetimeScope container, IPipelines pipelines)
        {
            // No registrations should be performed in here, however you may
            // resolve things that are needed during application startup.
        }

        protected override void ConfigureApplicationContainer(ILifetimeScope existingContainer)
        {
            // Perform registration that should have an application lifetime
        }

        protected override void ConfigureRequestContainer(ILifetimeScope container, NancyContext context)
        {
            // Perform registrations that should have a request lifetime
        }

        protected override void RequestStartup(ILifetimeScope container, IPipelines pipelines, NancyContext context)
        {
            // No registrations should be performed in here, however you may
            // resolve things that are needed during request startup.
        }
    }
}
```

files

Message:

```
Located multiple bootstrappers:
 - BootstrapperBug.Bootstrapper
 - Nancy.DefaultNancyBootstrapper

Either remove unused bootstrapper types or specify which type to use.
```

Stacktrace:
```
   at Nancy.Bootstrapper.NancyBootstrapperLocator.GetBootstrapperType()
   at Nancy.Bootstrapper.NancyBootstrapperLocator.LocateBootstrapper()
   at Nancy.Bootstrapper.NancyBootstrapperLocator.get_Bootstrapper()
   at Nancy.Owin.NancyOptions.get_Bootstrapper()
   at Nancy.Owin.NancyMiddleware.UseNancy(NancyOptions options)
   at Nancy.Owin.DelegateExtensions.UseNancy(Action`1 builder, NancyOptions options)
   at BootstrapperBug.Startup.<>c.<Configure>b__1_0(Action`1 x) in C:\Users\CMENGU\Desktop\BootstrapperBug\src\BootstrapperBug\Startup.cs:line 32
   at Microsoft.AspNetCore.Builder.OwinExtensions.UseOwin(IApplicationBuilder builder, Action`1 pipeline)
   at BootstrapperBug.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\CMENGU\Desktop\BootstrapperBug\src\BootstrapperBug\Startup.cs:line 32
```

### Details
- Nancy version: 2.0.0-barneyrubble
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
"Nancy": "2.0.0-barneyrubble",
"Nancy.Bootstrappers.Autofac": "2.0.0-Pre472",
"Microsoft.AspNetCore.Owin": "1.1.0-preview1-final"
- Environment (Operating system, version and so on): Windows
- .NET Framework version: netstandard1.6 / net452

### PR DESCRIPTION
**Pull request by cemremengu**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided KHELLANG TESTING

### Description

Fixes #2617

### CODE REVIEW

**Comment by cemremengu** [comment]
@thecodejunkie I think that is gone. There used to be a `ScanMode.ExcludeNancy` thing but removed now, if you are talking about that.

**Comment by thecodejunkie** [comment]
Yeah I think we removed the overload before we submitted the final version of IAssemblyCatalog 

Will review it properly when I'm at a computer

**Comment by cemremengu** [comment]
Without that the best we can do is:

```
        private static IEnumerable<Assembly> GetNancyReferencingAssemblies()
        {
#if CORE
            var assemblyCatalog =
                new DependencyContextAssemblyCatalog();

            return assemblyCatalog.GetAssemblies().Where(x => !x.Equals(typeof(NancyEngine).GetAssembly()));
#else
            return AppDomain.CurrentDomain.GetAssemblies().Where(IsNancyReferencing).Where(assembly => !assembly.ReflectionOnly && !x.Equals(typeof(NancyEngine).GetAssembly()));
#endif
        }
```

me thinks

**Comment by khellang** [comment]
Just wrap the assembly catalog in a `DefaultTypeCatalog`. I think we should implement a `StaticAssemblyCatalog` which simply takes a list of assemblies. So instead of returning `IEnumerable<Assembly>`, the method can return a `IAssemblyCatalog`, then wrap it in a `DefaultTypeCatalog` and use `GetTypesAssignableTo<IBootstrapper>(TypeResolveStrategies.ExcludeNancy)`.

**Comment by khellang** [comment]
Actually, why are we even getting the types manually from the `AppDomain` when we have the `AppDomainAssemblyCatalog`?

**Comment by cemremengu** [comment]
Seems like `AppDomainAssemblyCatalog` does not work for net core ?

**Comment by khellang** [comment]
> Seems like `AppDomainAssemblyCatalog` does not work for net core ?

Sure, but this branch is not for core anyway :smile:

```csharp
private static IEnumerable<Assembly> GetNancyReferencingAssemblies()
{
#if CORE
        return new DependencyContextAssemblyCatalog();
#else
        return new AppDomainAssemblyCatalog();
#endif
}
```

**Comment by khellang** [comment]
I think this looks good. Would it be possible to write some tests for this? I'm worried that we'll break someone by introducing regressions.

**Comment by thecodejunkie** [comment]
👀

**Comment by thecodejunkie** [comment]
@cemremengu can you rebase this please?

**Comment by thecodejunkie** [comment]
Merged, @cemremengu would look into adding tests as a separate pull-request when his workload allows it

**Pull request merged**
