### PR TITLE
Removed TaskCompletionSource usage from Route<T>.Invoke for #2623

### PR DESCRIPTION
**Pull request by davidallyoung**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)

### Description

This PR implements removal of the `TaskCompletionSource` that was causing a performance issue as reported in #2623. It converts the `Route<T>.Invoke` to be an async method signature and just returns the awaited Action.Invoke call.

I attempted to resolve this using the suggestion to return the raw result of Action.Invoke without awaiting from @damianh  and @grumpydev, however the signature of the base method is `Task<object>` and you cannot cast `Task<T>` (the return type of the `Action`) to `Task<object>` without doing various hoops (such as the `TaskCompletionSource` method that was being used).

### CODE REVIEW

**Comment by thecodejunkie** [comment]
👀 @NancyFx/most-valued-minions

**Comment by thecodejunkie** [comment]
Can you rebase please? It will hopefully fix the Travis build error since we've pull in #2685

**Comment by thecodejunkie** [comment]
Does not look like this rebase it correct. It is now showing commits by me and @jchannon as well

image

If you are unsure how to rebase, this guide https://github.com/NancyFx/Nancy/blob/master/.github/CONTRIBUTING.md provides some assistance.

Thanks!

**Comment by davidallyoung** [comment]
@thecodejunkie oops sorry about that, VS github plugin trolled me when I pressed sync :(. We should be good now assuming the build completes.

**Comment by thecodejunkie** [comment]
Would this exhibit the same behavior, as the previous code, in case of an exception?

> `task.ContinueWith(t => tcs.SetException(t.Exception.InnerExceptions), TaskContinuationOptions.OnlyOnFaulted);`

Making sure we end up with the correct exception?

Additional feedback @khellang @damianh ?

**Comment by khellang** [comment]
TBH I can't remember why we did it this way in the first place. I think the problem is that the action returns `Task<T>`, while we want `Task<object>`, so instead of going `async`/`await`, we wanted to try to avoid the state machine. If this gives better perf, I think this change is fine.

**Comment by khellang** [comment]
Oh, and now I read the description which I pretty much re-hashed in my previous comment :stuck_out_tongue_closed_eyes:

**Pull request merged**
