### PR TITLE
Ensure http verbs are compared in a case insensitive way

### LINKED ISSUE #2119: _method in form request is case sensative
Version 1.1
It appears that the ParseFormData() in the Request which reads the _method value from submitted form data is case sensitive. Lower case methods cause a 405 error to be thrown in our application.

The following call throws a 405
Example:
POST http://localhost:8080/route
Body:
_method=post

The following is handled by the route
Example:
POST http://localhost:8080/route
Body:
_method=POST

### PR DESCRIPTION
**Pull request by xt0rted**
This should resolve #2119. I used `.ToUpperInvariant()` because it's what was used in [DefaultRequestDispatcher.cs#L72](https://github.com/NancyFx/Nancy/blob/df8722d11e983029446d48d5b08740d9dad24218/src/Nancy/Routing/DefaultRequestDispatcher.cs#L72)

This also removes the multiple enumeration of `providedOverride` but if we don't want to make that change I can revert it.

### CODE REVIEW

**Comment by thecodejunkie** [comment]
Hi

Thanks! Could you change the use of `ToUpperInvariant()` to `.Equals(..., StringComparison.OrdinalIgnoreCase)` ?

**Comment by xt0rted** [comment]
@thecodejunkie I don't think this can be changed to use `.Equals()` since there isn't a comparison being made.

**Comment by khellang** [comment]
I think instead of doing this, we should change the comparisons all over the place - they're pretty inconsistent;

https://github.com/NancyFx/Nancy/blob/df8722d11e983029446d48d5b08740d9dad24218/src/Nancy/Routing/DefaultRequestDispatcher.cs#L72 -> OrdinalIgnoreCase
https://github.com/NancyFx/Nancy/blob/df8722d11e983029446d48d5b08740d9dad24218/src/Nancy/Routing/DefaultRouteResolver.cs#L166 -> OrdinalIgnoreCase
https://github.com/NancyFx/Nancy/blob/df8722d11e983029446d48d5b08740d9dad24218/src/Nancy/Routing/Trie/RouteResolverTrie.cs#L17 -> OrdinalIgnoreCase (for the dictionary keys)

@xt0rted Would you mind changing them and see if the test pass then?

**Comment by khellang** [comment]
https://github.com/NancyFx/Nancy/blob/df8722d11e983029446d48d5b08740d9dad24218/src/Nancy/Routing/Trie/RouteResolverTrie.cs#L17

^ That's where the "error" is. If you add `OrdinalIgnoreCase` to the dictionary, the test passes.

**Comment by khellang** [comment]
See https://github.com/khellang/Nancy/commit/d801451ae8c80b67bd11b6b8ccf42259a9705d46

**Comment by khellang** [comment]
```diff
diff --git a/src/Nancy.Tests.Functional/Tests/MethodRewriteFixture.cs b/src/Nancy.Tests.Functional/Tests/MethodRewriteFixture.cs
index a69c244..f266668 100644
--- a/src/Nancy.Tests.Functional/Tests/MethodRewriteFixture.cs
+++ b/src/Nancy.Tests.Functional/Tests/MethodRewriteFixture.cs
@@ -1,14 +1,13 @@
 namespace Nancy.Tests.Functional.Tests
 {
     using System;
-
-    using Nancy.Testing;
-
+    using Testing;
     using Xunit;
+    using Xunit.Extensions;
 
     public class MethodRewriteFixture
     {
-        private Browser browser;
+        private readonly Browser browser;
 
         public MethodRewriteFixture()
         {
@@ -18,12 +17,15 @@ public MethodRewriteFixture()
             });
         }
 
-        [Fact]
-        public void Should_rewrite_method_when_method_form_input_is_provided()
+        [Theory]
+        [InlineData("delete")]
+        [InlineData("dElEtE")]
+        [InlineData("DELETE")]
+        public void Should_rewrite_method_when_method_form_input_is_provided(string method)
         {
             var response = this.browser.Post("/", with =>
             {
-                with.FormValue("_method", "DELETE");
+                with.FormValue("_method", method);
             });
 
             Assert.Equal("Delete route", response.Body.AsString());
@@ -103,4 +105,4 @@ public MethodRewriteModule()
             };
         }
     }
-}
\ No newline at end of file
+}
diff --git a/src/Nancy/Diagnostics/DiagnosticsHook.cs b/src/Nancy/Diagnostics/DiagnosticsHook.cs
index 66734be..214c148 100644
--- a/src/Nancy/Diagnostics/DiagnosticsHook.cs
+++ b/src/Nancy/Diagnostics/DiagnosticsHook.cs
@@ -147,7 +147,7 @@ private static Response ExecuteDiagnostics(NancyContext ctx, IRouteResolver rout
                 ctx.Response = task.Result;
             }
 
-            if (ctx.Request.Method.ToUpperInvariant() == "HEAD")
+            if (ctx.Request.Method.Equals("HEAD", StringComparison.OrdinalIgnoreCase))
             {
                 ctx.Response = new HeadResponse(ctx.Response);
             }
@@ -253,7 +253,7 @@ private static DiagnosticsSession ProcessLogin(NancyContext context, Diagnostics
 
         private static bool IsLoginRequest(NancyContext context, DiagnosticsConfiguration diagnosticsConfiguration)
         {
-            return context.Request.Method == "POST" &&
+            return context.Request.Method.Equals("POST", StringComparison.OrdinalIgnoreCase) &&
                 context.Request.Url.BasePath.TrimEnd(new[] { '/' }).EndsWith(diagnosticsConfiguration.Path) &&
                 context.Request.Url.Path == "/";
         }
diff --git a/src/Nancy/Routing/DefaultRequestDispatcher.cs b/src/Nancy/Routing/DefaultRequestDispatcher.cs
index a36396c..d25d11f 100644
--- a/src/Nancy/Routing/DefaultRequestDispatcher.cs
+++ b/src/Nancy/Routing/DefaultRequestDispatcher.cs
@@ -69,7 +69,7 @@ public Task<Response> Dispatch(NancyContext context, CancellationToken cancellat
                                     {
                                         context.Response = completedRouteTask.Result;
 
-                                        if (context.Request.Method.ToUpperInvariant() == "HEAD")
+                                        if (context.Request.Method.Equals("HEAD", StringComparison.OrdinalIgnoreCase))
                                         {
                                             context.Response = new HeadResponse(context.Response);
                                         }
diff --git a/src/Nancy/Routing/DefaultRouteResolver.cs b/src/Nancy/Routing/DefaultRouteResolver.cs
index 9647785..68f50b9 100644
--- a/src/Nancy/Routing/DefaultRouteResolver.cs
+++ b/src/Nancy/Routing/DefaultRouteResolver.cs
@@ -93,7 +93,7 @@ private static bool IsMethodNotAllowed(IEnumerable<string> allowedMethods)
 
         private static bool IsOptionsRequest(NancyContext context)
         {
-            return context.Request.Method.Equals("OPTIONS", StringComparison.Ordinal);
+            return context.Request.Method.Equals("OPTIONS", StringComparison.OrdinalIgnoreCase);
         }
 
         private void BuildTrie()
@@ -163,7 +163,7 @@ private static string GetMethod(NancyContext context)
 
             if (!StaticConfiguration.EnableHeadRouting)
             {
-                return requestedMethod.Equals("HEAD", StringComparison.Ordinal) ?
+                return requestedMethod.Equals("HEAD", StringComparison.OrdinalIgnoreCase) ?
                     "GET" :
                     requestedMethod;
             }
diff --git a/src/Nancy/Routing/Trie/RouteResolverTrie.cs b/src/Nancy/Routing/Trie/RouteResolverTrie.cs
index f8d755a..dc1e62d 100644
--- a/src/Nancy/Routing/Trie/RouteResolverTrie.cs
+++ b/src/Nancy/Routing/Trie/RouteResolverTrie.cs
@@ -14,7 +14,7 @@ public class RouteResolverTrie : IRouteResolverTrie
     {
         private readonly ITrieNodeFactory nodeFactory;
 
-        private readonly IDictionary<string, TrieNode> routeTries = new Dictionary<string, TrieNode>();
+        private readonly IDictionary<string, TrieNode> routeTries = new Dictionary<string, TrieNode>(StringComparer.OrdinalIgnoreCase);
 
         private static char[] splitSeparators = new[] {'/'};
 
@@ -117,4 +117,4 @@ public override string ToString()
             return sb.ToString();
         }
     }
-}
\ No newline at end of file
+}
```

**Comment by xt0rted** [comment]
@khellang here's another try at fixing it. I wasn't sure if there were other tests that needed to be added/updated.

For some reason running the tests locally with resharper results in [When_AutoRegistration_Is_Enabled_Should_Throw](https://github.com/NancyFx/Nancy/blob/df8722d11e983029446d48d5b08740d9dad24218/src/Nancy.Tests/NoAppStartupsFixture.cs#L59) always being marked as failed. I think it's just the test runner though because on travis & teamcity this is passing.

**Comment by khellang** [comment]
Yes! This looks better. Let me have a look when I get to a computer :+1:

**Comment by khellang** [comment]
Thanks! :heart:

**Pull request merged**
