### PR TITLE
install FakeItEasy.Analyzer and remove one redundant call

### PR DESCRIPTION
**Pull request by adamralph**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)

### Description
As it says on the tin.

### CODE REVIEW

**Comment by adamralph** [comment]
I've no idea what the test failures are all about. They seem unrelated to my changes, and all the tests pass on my machine.

**Comment by adamralph** [comment]
rebased

**Comment by adamralph** [comment]
I amended the commit so that all the "new" (project.json) projects have the analyzer installed as well as the "old".

**Comment by jchannon** [comment]
What is FakeItEasy.Analyzer?

**Comment by khellang** [comment]
I'm not sure there's any point in adding this package to the project.json files as, AFAIK, they're not supported. Also, just curious, why is it not shipped within the FakeItEasy package?

**Comment by adamralph** [comment]
@jchannon it's a Roslyn analyzer for FIE. At the moment, it only contains one diagnostic, which warns against unused (and therefore redundant call configurations, e.g. https://github.com/NancyFx/Nancy/pull/2492/files#diff-ceb473a964e6cbafdd42900d3c447fa8L21

@khellang it seems to be supported:

image

The squiggles are missing underneath the line of code for some reason, but the diagnostic is being run, as the error window shows.

We debated putting the analyzer in the main package, see the poll and the thread at https://twitter.com/adamralph/status/726465900384272385

**Comment by khellang** [comment]
Ah, looks like it's been added; https://github.com/dotnet/cli/pull/927. Nice. I thought they weren't going to add that to project.json since it's going away...

**Comment by jchannon** [comment]
@adamralph fancy a rebase and I'll merge?

**Comment by adamralph** [comment]
@jchannon sure. There you go...

**Comment by jchannon** [comment]
:heart:

**Comment by adamralph** [comment]
:dancers:

**Comment by adamralph** [comment]
@jchannon thanks for the merge. Here's a PR to upgrade both FIE and the analyzer to 2.2.0 - #2560

**Pull request merged**
