### PR TITLE
re-enable test parallelisation after the upgrade to FakeItEasy 2.0.0

### PR DESCRIPTION
**Pull request by adamralph**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)

### Description
As it says on the tin, except `Nancy.ViewEngines.DotLiquid`, which suffers from a thread safety issue unrelated to FakeItEasy 1.x.

### CODE REVIEW

**Comment by khellang** [comment]
Awesome. Thanks! :+1:

**Comment by adamralph** [comment]
@khellang out of interest did you use "Squash and Merge" on this PR?

image

image

**Comment by khellang** [comment]
Not sure. I clicked the big Green button in the GH UI :smile:

**Comment by adamralph** [comment]
IIRC it remembers your last choice, even if it was in another repo.

Personally, I don't like the feature. I switch it off in all my repos.

**Comment by khellang** [comment]
> Personally, I don't like the feature. I switch it off in all my repos.

Why, exactly?

**Comment by adamralph** [comment]
1. I don't like fast forward merges to master. I like to see the merges from PR branches in the history to prove that master was merged to rather than direct pushed.
1. It effectively does an amend to the commits, as well as the merge. In FakeItEasy we don't like that. We want the *actual* commits that are going to be merged to be visible in the PR for everyone to see (and approve) and the only action taken by the merging maintainer to be "merge".
1. It's too easy to press by accident (as you've found out :wink:), compounded by the fact that the UI remembers your last choice. It's better to have a squash as an explicit request to the contributor or in a superseding PR from another maintainer, so the only action possible is "merge", preventing a mistake one way or the other. These mistakes either have to be left as-is, or fixed by a force push (also banned in all the repos I work on).
1. It strips GPG signatures.

**Pull request merged**
