### PR TITLE
use bundle instead of installing gems seperatly

### PR DESCRIPTION
**Pull request by tparnell8**
#1953 Probably want to run bundle and use the gem file...

### CODE REVIEW

**Comment by tparnell8** [comment]
I assume someone will have to alter the Team City build. This lets PR's use other gems.

**Comment by khellang** [comment]
I'm not really into Ruby, rake, bundle and gems. How come TC says this is all good?

**Comment by tparnell8** [comment]
The main problem is that if someone submits a PR to alter the rake file that will require a new gem (ruby version of a nuget package) the build will fail. This is because you have to call bundle before you start calling rake. bundle is essentially a gem that will download all the gems listed in the gemfile. Very similar to calling a nuget restore. This PR contains the commands to alter travis, but you will also need to make the modification in TC, by simply having it call bundle before it does any rake tasks.

**Comment by tparnell8** [comment]
As a side note, you are using the release candidate of version 1 of albacore, albacore is now on 2.4.2. You may want to consider updating at some point.

**Comment by grumpydev** [comment]
The bundle file was there because it looked like Travis needed it but it isn't actually used.. Whether we delete it or change scripts to use it I am not too fussed. 

As for albacore, there are too many breaking changes to be worth the effort of switching versions, it would effectively mean a complete rewrite of our build scripts, which just isn't worth investing the time in when they work fine as they are.

**Comment by thecodejunkie** [comment]
Did we reach a consensus on this one?

**Comment by tparnell8** [comment]
this change fixes the gem file. Basically its like a packages.config. My change pins ruby to the specific version of albacore that is required by your rake file.

Anyone familiar with ruby will try to run bundle (which is like nuget restore) which will give them the latest version of albacore. The problem (which again is not too big of a deal) is that your rakefile needs a specific version of albacore. This was why you were having travis installing the specific version of albacore, but what you really want (what is best practice in ruby) is to fix the gemfile, and then have travis use the gemfile.

If you get a newer version of albacore (like version 2) the rake file will not work (which was also why your travis build was doing . 

When I checked this out on my ubuntu box I could not do a build with rake because I needed the proper gem (which was not specified in the gemfile).

**Comment by khellang** [comment]
:+1:

**Pull request merged**
