### PR TITLE
Added .mailmap

### PR DESCRIPTION
**Pull request by khellang**
:sparkles:

### CODE REVIEW

**Comment by grumpydev** [comment]
What's this do?

**Comment by thecodejunkie** [comment]
@grumpydev http://stacktoheap.com/blog/2013/01/06/using-mailmap-to-fix-authors-list-in-git/

**Comment by grumpydev** [comment]
Other than put my personal email address on the internet that is :|

**Comment by thecodejunkie** [comment]
It looks like it's messing up the `å` character though, even with Unicode encoding in my browser

**Comment by thecodejunkie** [comment]
@grumpydev those e-mail addresses are already here on github in the commit log as it's the e-mails you've committed with

**Comment by grumpydev** [comment]
All my machines are set to my gmail account, don't remember ever using the other one because I prefer to keep it private.. was it ages and ages ago?

**Comment by khellang** [comment]
@grumpydev LOL, you've already put those emails on the internetz. See [this patch](https://github.com/NancyFx/Nancy/commit/188bc90450b10d263495d0a33c4cec98a1903937.patch).

**Comment by thecodejunkie** [comment]
Is that supposed to be human readable? :P

**Comment by grumpydev** [comment]
Your name causes so many issues @thecodejunkie - I think we should take a vote on you changing it to something with normal letters in ;)

**Comment by khellang** [comment]
@thecodejunkie That commit in particular was a binary patch :smile:

**Comment by thecodejunkie** [comment]
@grumpydev "God" will do ;)

**Comment by grumpydev** [comment]
Looks like pressing the big green button in github make a merge commit with my proper email address.. that's a bit irritating.

**Comment by thecodejunkie** [comment]
Is that set as the default one on your account?

**Comment by grumpydev** [comment]
My settings are set to "do not show my email", but then when I click on "personal email settings" it shows it as public and primary, yay for contradictory settings :)

**Comment by khellang** [comment]
We might have to figure out the encoding on this before it goes in...

**Comment by grumpydev** [comment]
image

Not seen that option before.

**Comment by thecodejunkie** [comment]
I just check and I had that ticked :P
hasn't stopped me from accidentally setting up a local git setup with the wrong account though ;)

**Comment by grumpydev** [comment]
Just checked it on mine.. guess I need grumpydev@users.noreply.github.com adding too :)

**Comment by khellang** [comment]
@grumpydev I amended the .mailmap to reflect your new "public" email :wink:

```
  1347  Andreas H<E5>kansson <andreas@thecodejunkie.com>
  1237  Steven Robbins <grumpydev@users.noreply.github.com>
   218  Kristian Hellang <kristian@hellang.com>
   173  Jonathan Channon <jonathan.channon@gmail.com>
    78  Phillip Haydon <phillip.haydon@gmail.com>
    72  prabirshrestha <mail@prabir.me>
    65  Damian Hickey <dhickey@gmail.com>
    60  Albert-Jan Nijburg <albertjan@curit.com>
    56  Christian Horsdal <c.horsdal@gmail.com>
    36  Mindaugas Mozuras <mindaugas.mozuras@gmail.com>
    33  Brian Surowiec <xtorted@optonline.net>
    31  Adrian D. Alvarez <adrian@adriandalvarez.com>
    30  Jim Liddell <liddell_j@hotmail.com>
```

**Comment by grumpydev** [comment]
Who's Andreas H<E5>kansson ? ;)

**Comment by thecodejunkie** [comment]
I feel like a victim of online harassment!

**Comment by thecodejunkie** [comment]
å copy and paste it ;)

**Comment by thecodejunkie** [comment]
@khellang there.. nailed it ;)

**Comment by khellang** [comment]
Weeeee! UTF-8 :lipstick:

**Comment by grumpydev** [comment]
You're the BOM! (geddit? ;))

**Comment by thecodejunkie** [comment]
@grumpydev Conflicted.. not sure if I hate myself more for laughing our you for making the joke ;)

**Comment by grumpydev** [comment]
:dancer:

**Comment by albertjan** [comment]
http://www.urbandictionary.com/define.php?term=FEFF

**Comment by phillip-haydon** [comment]
Fuck. Now everyone knows how to contact me. No wonder I get so much spams now.

**Comment by khellang** [comment]
There's nothing to :eyes: here... Everything in this thread (and repository as a whole) is public information. That includes the emails you've used for commits :wink:

**Comment by phillip-haydon** [comment]
LOOK WHAT YOU'VE DONE!

image

**Pull request merged**
