### PR TITLE
bug fixing:the questionmark is lost when logging on and redirecting

### PR DESCRIPTION
**Pull request by Tsingbo-Kooboo**
Hi Nancy,
This is the fix like what https://github.com/NancyFx/Nancy/issues/1866 said,discard this if you have better way to fix.Thx!

### CODE REVIEW

**Comment by khellang** [comment]
@Tsingbo-Kooboo There's 4 tests failing now. Want to look at them? http://nancy-ci.cloudapp.net/viewLog.html?buildId=2119&buildTypeId=Nancy_Pulls

**Comment by khellang** [comment]
Several others have mentioned the same on JabbR etc. without filing a bug for it. We'd love to get this bug fixed once and for all, but the tests seem to suggest that the questionmark should be present in the query string. Don't know what's going on.

**Comment by khellang** [comment]
Ah, I see what's going on. The tests passes a query string containing `?` into the request, while the hosts doesn't. So the tests ends up with double `%3f`. What you could do is just remove the `?` from the test query strings.

**Comment by khellang** [comment]
OK, looks like `NancyHandler` (the `System.Web` host) [passes the raw `Uri.Query` to the request](https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Hosting.Aspnet/NancyHandler.cs#L87), which also should contain the `?`. Maybe it's just a matter of normalizing how the query is stored in `Url`? E.g. make the Query property of url backed by a field and doing

```csharp
public string Query
{
    get { return this.query; }
    set { this.query = value.TrimStart('?'); }
}
```

@NancyFx/owners @NancyFx/most-valued-minions What do you think?

**Comment by phillip-haydon** [comment]
I concur.

**Comment by horsdal** [comment]
:+1: for normalizing

**Comment by khellang** [comment]
@Tsingbo-Kooboo Thanks for providing a potential fix. It turned out to be a deeper problem (how the hosts handles the leading `?` in query strings). I sent a PR (#1870) which should solve this problem once and for all. Would you mind trying it out from the [CI feed](https://www.myget.org/gallery/nancyfx) and see if it solves your problem?

**Pull request closed without merging**
