### PR TITLE
Issue 2006. Fix reversed bools in comment on DefaultNancyBootstrapper.AutoRegisterIgnoredAssemblies

### PR DESCRIPTION
**Pull request by samal84**
https://github.com/NancyFx/Nancy/issues/2006

### CODE REVIEW

**Comment by khellang** [comment]
ProTip! If you include `Closes #2006`, `Fixes #2006`,  `Resolves #2006` etc. in the PR description, then GitHub will automatically close the issue when the PR is merged :wink: See [closing an issue in the same repository](https://help.github.com/articles/closing-issues-via-commit-messages/#closing-an-issue-in-the-same-repository)

**Comment by khellang** [comment]
Thanks for this @samal84! :heart:

**Comment by thecodejunkie** [comment]
Congratulations on becoming an OSS contributor :heart:

**Comment by jugglingnutcase** [comment]
:clap: @samal84 :clap:

**Pull request merged**
