### PR TITLE
[WIP] Coreclr - Nancy Project

### PR DESCRIPTION
**Pull request by Yantrio**
This is the beginning of the port to get things working on coreclr. 
See issue #2220

### CODE REVIEW

**Comment by jchannon** [comment]
Rebased  CoreCLR branch

**Comment by khellang** [comment]
Yeah... This won't work. That history is no good :stuck_out_tongue_closed_eyes:

**Comment by Yantrio** [comment]
Yeah, I know :( we tried, but can't seem to get github to update.

https://twitter.com/jchannon/status/694605837877276673

**Comment by jchannon** [comment]
Helpful. Explain why. The branch diff is fine
https://github.com/NancyFx/Nancy/compare/coreclr...VQComms:dnxcore50-initial-setup?expand=1

**Comment by khellang** [comment]
Also, we shouldn't target dnxcore50, that's for apps, Nancy is a framework :smile:

**Comment by Yantrio** [comment]
I'll switch to dotnet5.4 :)

**Comment by jchannon** [comment]
Again. What should it be?

**Comment by khellang** [comment]
> Again. What should it be?

It should be the lowest `dotnet5.x` we would like to support. That really depends on what APIs we need. For Serilog, we've been successfully targeting `dotnet5.1`, which means we effectively support anything in the .NET space.

**Comment by jchannon** [comment]
Further info for people https://github.com/aspnet/Announcements/issues/98

**Comment by khellang** [comment]
Also, when you're doing this work, it would be nice if you could document somewhere why dependencies are added, i.e. which types are being used or something. We want to keep the footprint for Nancy as small as possible and right not it looks like the kitchen sink is being added :wink:

**Comment by Yantrio** [comment]
Seems a bit over the top to document every dependency, i've only added ones that are needed so far (one by one) and each of them can be verified by finding their usages in the IDE of your choice.

**Comment by khellang** [comment]
> Seems a bit over the top to document every dependency

Why? It would help us tremendously when reviewing this, and also make it much easier to determine which types/packages/dependencies we might be able to shave off.

> i've only added ones that are needed so far (one by one)

Exactly. So it shouldn't be that hard to keep a document in Notepad or something saying "System.Net.Primitives - <some type(s)>". You're already adding the one by one :smile:

> each of them can be verified by finding their usages in the IDE of your choice

How? I've yet to see how you can check where a package is used.

**Comment by Yantrio** [comment]
I was under the impression VS let you view usages of references since Xamarin could. I mainly work in atom, so It's been a while since I used VS/Xamarin.

does anyone have suggestions/comments on how to replace some of the components mentioned in the first comment?

**Comment by jchannon** [comment]
Lets split all the comments into an issue and then each checkbox can be a PR

**Comment by Yantrio** [comment]
I've created issue #2220 so we can seperate this into seperate PRs and track it a bit easier.

**Comment by khellang** [comment]
> does anyone have suggestions/comments on how to replace some of the components mentioned in the first comment?

Which comment?

**Comment by Yantrio** [comment]
> Which comment?

That comment has now moved to #2220

**Comment by khellang** [comment]
> That comment has now moved to #2220

Added my $0.02 to that issue; https://github.com/NancyFx/Nancy/issues/2220#issuecomment-179162206

**Comment by Yantrio** [comment]
i've closed this because the diff comparison seems to be broke (gh support never got back to me) and i have cleaner PRs incoming

**Pull request closed without merging**
