### PR TITLE
Claims identity

### PR DESCRIPTION
**Pull request by felipeleusin**
This is a work in progress to help with issue #1800 .

My goal was to get the solution building and tests passing but there are two questions I need to know.

1) Should the concept of UserName in Nancy be converted to a claim of type Name? In IUserIdentity the concept of being Authorized is usually associate with a not empty UserName but a ClaimsIdentity has a IsAuthenticated property that makes a lot of sense to use it.

2) The Authentication.Token uses an specific spec for the tokens? If not, would be the case to switch to Jwt in v2 since they are somewhat Claims-friendly or it's better to adapt the current spec?

There is still a lot to do but I hope this can help with the grunt of the work

### CODE REVIEW

**Comment by khellang** [comment]
Umm... I think there's some double work going on with #1820... :disappointed:

**Comment by damianh** [comment]
Well shit. I probably have assigned #1820 to myself before working on it. :S

**Comment by felipeleusin** [comment]
no sweat. Since I saw nothing on #1800 I  assumed it was still up for
grabs. Gonna close this then

Em sex, 20 de fev de 2015 07:52, Damian Hickey <notifications@github.com>
escreveu:

**Comment by damianh** [comment]
Really sorry @felipeleusin , appreciate the effort.

**Comment by felipeleusin** [comment]
Relly don't worry... this didn't took much time and I got to learn about ClaimsPrincipal and similars that was a subject I could learn more. Was just hoping to contribute to Nancy since we use it extensively in my company but never had sent a PR. If there is anything else you guys need help with, let me know.

**Pull request closed without merging**
