### PR TITLE
Enabled C# 6.0 in Razor views.

### PR DESCRIPTION
**Pull request by Liversage**
Replaced `CSharpCodeProvider` used by `CSharpRazorViewRenderer` with the new "Roslyn" version from NuGet allowing C# 6.0 language features to be used in Razor views.

### CODE REVIEW

**Comment by thecodejunkie** [comment]
Hi @Liversage could you please rebase this and I will pull it in asap?

Thanks!

**Comment by Liversage** [comment]
@thecodejunkie I have rebased as requested.

**Comment by thecodejunkie** [comment]
Thanks,

I am going to cherry-pick your commits as part of #2278

**Comment by thecodejunkie** [comment]
Picked them into my PR

**Pull request closed without merging**
