### PR TITLE
Add MyGet Links to README

### PR DESCRIPTION
**Pull request by cemremengu**
Added myget repo link

### CODE REVIEW

**Comment by jchannon** [comment]
Can you change it to Appveyor rather than Latest

**Comment by thecodejunkie** [comment]
@jchannon why should it say `Appveyor`? `Latest build` (or similar) is more appropriate.. it's what it is, not how it was produced?

**Comment by jchannon** [comment]
Because we have a heading called CI builds then 2 sub headings called TC
and Travis

**Comment by jchannon** [comment]
Oh my bad, it was linking to Myget not appveyor,

**Comment by cemremengu** [comment]
I will write Latest Appveyor Build then ? :laughing:  Make you guys both happy

**Comment by thecodejunkie** [comment]
Well then it should link to the AppVeryor builds, like it does for TC, and not the artifacts. I agree that we should link to MyGet but I don't agree with this approach :D

**Comment by thecodejunkie** [comment]
I think we can have

CI Build
 - Appveyor
 - TeamCity
 - Travis or what ever

Latest build (of master)
  - Myget

**Comment by jchannon** [comment]
Yup, although we really need to get rid of TC at some point

**Comment by thecodejunkie** [comment]
@jchannon could you create an issue for it with a todo list of projects that needs to be done + instructions on what needs to be done. Like we did for the config stuff and I'll try an get some PRs in

**Comment by cemremengu** [comment]
Ok this should do it now :laughing:

**Comment by cemremengu** [comment]
Need a squash ?

**Comment by thecodejunkie** [comment]
Yeah please squash

**Comment by thecodejunkie** [comment]
can you also rebase it plz

**Comment by cemremengu** [comment]
@thecodejunkie :eyes:

**Comment by cemremengu** [comment]
We can put the myget build status badge as well instead of just the link

http://docs.myget.org/docs/reference/build-services#Build_Status_Badges

**Comment by thecodejunkie** [comment]
@cemremengu yeah please add the badge and remove the TC (team city) section as well - we're not using it anymore. Instead we should add it for AppVeyor https://www.appveyor.com/docs/status-badges/ since that's what we're using now https://ci.appveyor.com/api/projects/status/mpd9lbxvithu16vg that's the link to the AppVeyor build badge

**Comment by xt0rted** [comment]
The SVG version of the badge is `https://ci.appveyor.com/api/projects/status/mpd9lbxvithu16vg?svg=true`

**Comment by cemremengu** [comment]
@thecodejunkie ping pong

**Comment by xt0rted** [comment]
Here's the badge for MyGet if you want to put this in too `https://img.shields.io/myget/nancyfx/vpre/Nancy.svg?style=flat&label=myget`

**Pull request merged**
