### PR TITLE
Test to show binding to a List<T> property on a model fails

### PR DESCRIPTION
**Pull request by jchannon**
The binder should be able to bind to List <T> property on a model but currently doesn't.

### CODE REVIEW

**Comment by khellang** [comment]
@jchannon Are you expecting this to be pulled? I think we need an actual fix as well :wink:

**Comment by khellang** [comment]
Ping @jchannon! Are you planning on submitting a fix for this failing test as well? :smile:

**Comment by jchannon** [comment]
I think this is one for the model binder king @grumpydev

**Comment by jchannon** [comment]
Deleted and issue raised #2169

**Pull request closed without merging**
