### PR TITLE
Module based authentication setup.

### PR DESCRIPTION
**Pull request by PureKrome**
- Added `INancyModule` constructors for Stateless Authentication and Forms Authentication.
- Unit tests for Forms Authentication. Note: There's no unit tests for Stateless Authentication.

woot

### CODE REVIEW

**Comment by khellang** [comment]
O happy day! :balloon:

**Comment by PureKrome** [comment]
@khellang ta mate :smile: 

question: is this available via the myget nightlies, now?

**Comment by khellang** [comment]
@PureKrome Yeah. I don't think they're nightlies. I think it's a CI feed. A couple of minutes after things are merged to master, they're available in the [myget feed](https://www.myget.org/gallery/nancyfx) :grin:

**Comment by PureKrome** [comment]
Even better. ta!

**Comment by albertjan** [comment]
@khellang @PureKrome needs docs?

**Comment by PureKrome** [comment]
definately.

**Comment by khellang** [comment]
@PureKrome Did you add some lines in the wiki on this?

**Comment by PureKrome** [comment]
Nope, not yet. I'll get onto it today (hopefully).

**Comment by PureKrome** [comment]
- [Stateless authentication](https://github.com/NancyFx/Nancy/wiki/Stateless-authentication) page updated.
- [Forms authentication](https://github.com/NancyFx/Nancy/wiki/Forms-authentication) page also updated.

[Party!!](http://i.giphy.com/V0BIjUQRfl8tO.gif)

**Comment by khellang** [comment]
:+1:

**Pull request merged**
