### PR TITLE
nancy forms auth on coreclr

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by khellang** [comment]
Where's the xproj/sln changes?

**Comment by jchannon** [comment]
there isnt any

**Comment by khellang** [comment]
Ah, now I see. You just added `dotnet5.4`. It would be nice if you kept the diff cleaner so it would be easier to see what changed :smile:

**Comment by jchannon** [comment]
i used ctrl+K+D to format the json according to VS

**Comment by khellang** [comment]
Yeah, please keep formatting changes separate -- at least until things been reviewed. Then you can squash. This isn't easy to review:

image

**Comment by jchannon** [comment]
You're a big boy, I'm sure you can manager :wink: 

Try adding a `?w=1` that should do the trick

**Comment by phillip-haydon** [comment]
4 space tabbing please. Fix this!

**Comment by jchannon** [comment]
How do you change this in VS? I'm using their defaults

**Comment by phillip-haydon** [comment]
vs

**Comment by jchannon** [comment]
Cool, just found it.

Wonder if we could enforce that in our R# dotsettings file? Although I imagine when you ctrl+k+d, R# won't intercept that

**Comment by jchannon** [comment]
Reformatted

**Pull request merged**
