### PR TITLE
Added global.json and pinned SDK version

### PR DESCRIPTION
**Pull request by thecodejunkie**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [X] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [X] I have provided test coverage for my change (where applicable)

### Description
Added back the `global.json` file and pinned our SDK to 1.0.4

### CODE REVIEW

**Comment by jchannon** [comment]
Projects array is no longer supported as the solution file takes care of that. Only the Sdk version is needed

**Comment by thecodejunkie** [comment]
@jchannon updated. I've just gone with `1.0.4` - maybe we should go with `1.1.4` now instead? No point on sticking on an older `1.x` release is there? @khellang

**Comment by jchannon** [comment]
Can do but you might find you'll need to update some package versions too in Nancy etc

**Comment by thecodejunkie** [comment]
Maybe we pull in this one and treat that as a separate PR? There are some tooling stuff that's fixed post 1.0.4 which would be nice to have access to

**Pull request merged**
