### PR TITLE
Merge coreclr branch into master

### PR DESCRIPTION
**Pull request by thecodejunkie**
:scream: 

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)

### Description
Let's do this!

### CODE REVIEW

**Comment by Yantrio** [comment]
https://media.giphy.com/media/2Faz8bcnGfXVrV2ZG/giphy.gif

**Comment by khellang** [comment]
PARTY

**Comment by grumpydev** [comment]
This Pull Request has too many commits and violates the Single Pull Request Responsibility Principal so we can't merge it in, sorry - better luck next time.

**Pull request closed without merging**
