### PR TITLE
Fix typos & whitespace on TinyIoC

### PR DESCRIPTION
**Pull request by 06b**
Converted tabs to spaces & removed some trailing white space.

Fixed following typos:
registation(s) -> registration(s) 
Attemps -> Attempts 
sucessfully -> successfully
Attemped -> Attempted

### CODE REVIEW

**Comment by khellang** [comment]
I'm not 100% sure this is the right repo for this. I think we'd rather pull a new version from https://github.com/grumpydev/TinyIoC.

**Comment by 06b** [comment]
Ah, wasn't sure because I noticed pull request/issues for SSVE in the Nancy repo rather than the SSVE repo, so I thought the same applied for TinyIoC.

I'll send a pull request in the TinyIoC repo later and I can close this one when I do that.

**Comment by thecodejunkie** [comment]
Let's just loop in @grumpydev  and have him decide where he wants it

**Comment by phillip-haydon** [comment]
It should be updated in both. Last time I did something it had to be accepted into TinyIoC project then accepted in Nancy to keep the two in sync. So two PRs. Can merge this when its merged into TinyIoC unless @grumpydev wants to go down a different path and ditch his repo.

**Comment by khellang** [comment]
I'm closing this. Feel free to open up a PR with a new version of TinyIoC if/when https://github.com/grumpydev/TinyIoC/pull/83 is pulled :smile:

**Comment by khellang** [comment]
@06b You might also want to include the TinyIoC.cs part of https://github.com/06b/Nancy/commit/f6051d8011e1d71d8207c29aa5bd31e4b0d80dcf in your PR as well? That's something that's been pulled into Nancy, which probably haven't been pushed upstream.

**Pull request closed without merging**
