### PR TITLE
Await call to Process in NancyHost

### PR DESCRIPTION
**Pull request by jchannon**
pinging @damianh :smile:

### CODE REVIEW

**Comment by damianh** [comment]
No, don't do this, it will serialize (sequential-ize) handling of requests.

**Comment by jchannon** [comment]
:confounded:

**Comment by grumpydev** [comment]
The way it is currently setup though you have an unobserved task which may randomly blow up the appdomain?

**Comment by damianh** [comment]
@grumpydev not on .net 4.5 unless you...

```
<configuration> 
    <runtime> 
        <ThrowUnobservedTaskExceptions enabled="true"/> 
    </runtime> 
</configuration>
```

There is also some good exception handling coverage. https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Hosting.Self/NancyHost.cs#L412-L430

Though this https://github.com/NancyFx/Nancy/blob/master/src/Nancy.Hosting.Self/NancyHost.cs#L429 could be wrapped in a try-catch as it reaches out to external code.

**Comment by grumpydev** [comment]
Still feels wrong to me having a method marked as async and returning a Task but ignoring it :/

**Comment by damianh** [comment]
Yeah a `Task.Run(() => Process(context));` would be more aesthetic.

**Pull request closed without merging**
