### PR TITLE
Disable appdomains for xunit on Mono

### PR DESCRIPTION
**Pull request by akoeplinger**
This should fix the instability you're seeing on Travis.

Mono bug is tracked at https://bugzilla.xamarin.com/show_bug.cgi?id=39251

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, looks like some tests can't find views anymore, presumably because without appdomains  shadow-copy is disabled too: 

```
Nancy.Testing.Tests.TestingViewExtensions.GetModuleNameExtensionTests.should_return_name_of_the_module [FAIL]
      System.Exception : ConfigurableBootstrapper Exception
      ---- Nancy.RequestExecutionException : Oh noes!
      -------- Nancy.ViewEngines.ViewNotFoundException : Unable to locate view 'TestingViewExtensions/ViewFactoryTest.sshtml'
      Currently available view engine extensions: sshtml,html,htm
      Locations inspected: views/TestingViewFactoryTest/TestingViewExtensions/ViewFactoryTest.sshtml-en-US,views/TestingViewFactoryTest/TestingViewExtensions/ViewFactoryTest.sshtml,TestingViewFactoryTest/TestingViewExtensions/ViewFactoryTest.sshtml-en-US,TestingViewFactoryTest/TestingViewExtensions/ViewFactoryTest.sshtml,views/TestingViewExtensions/ViewFactoryTest.sshtml-en-US,views/TestingViewExtensions/ViewFactoryTest.sshtml,TestingViewExtensions/ViewFactoryTest.sshtml-en-US,TestingViewExtensions/ViewFactoryTest.sshtml
      Root path: /home/travis/build/NancyFx/Nancy/tools/xunit/
```

Is there a way to override that?

**Comment by thecodejunkie** [comment]
@akoeplinger override what? The tests uses views, which need to be located on a relative path to the executing application.

**Comment by thecodejunkie** [comment]
@akoeplinger oh @khellang pointed out what I missed.. the invalid root path =)

**Comment by akoeplinger** [comment]
I think https://github.com/NancyFx/Nancy/blob/4c8d8e7b01d5e58f5e99c91799e06dca63e0bd31/src/Nancy/DefaultRootPathProvider.cs#L19 is the culprit. I assume that when the tests run in a separate AppDomain, that path points to the test dll path, but without it it points to where xunit.console.exe lives.

**Comment by thecodejunkie** [comment]
@akoeplinger yep, that's the same thing I'm looking at right now =)

**Comment by akoeplinger** [comment]
I pushed a new version which simply copies xunit.console.exe to the test directory so the base directory of the AppDomain is the expected one. Looks like everything is green now :)

**Comment by jchannon** [comment]
Thanks :heart:

**Pull request merged**
