### PR TITLE
Replaced powershell scripts with MSBuild target

### PR DESCRIPTION
**Pull request by thecodejunkie**
The name of the custom target file is `Nancy.ViewEngines.Razor.targets` and it has to have that name by convention. It adds two copy task that puts the `Nancy.ViewEngine.Razor.dll` and `Nancy.ViewEngine.Razor.BuildProviders.dll` files in `\bin`. This is where they need to be for intellisense to work. For console apps, they cannot be in `\bin\Debug\` or `\bin\Release` or I would simply have used `${Outputdir}`.

I've build the nuget locally `nuget pack nancy.viewengines.razor.nuspec` and setup a local nuget repo where I've installed into both a web and a console application project. The files will also only be copied if the build configuration is `DEBUG`.

All of this should be the same behavior we had with the `.ps1` files

### CODE REVIEW

**Comment by khellang** [comment]
:heart:

**Comment by thecodejunkie** [comment]
@grumpydev did you test the package locally? :)

**Comment by grumpydev** [comment]
Nope, was going to test the CI build package.

**Comment by thecodejunkie** [comment]
Ah. Cool =)

**Comment by xt0rted** [comment]
This should resolve #1621 and #1747

**Comment by khellang** [comment]
@xt0rted Thanks. Closed :+1:

**Pull request merged**
