### PR TITLE
Convert more tests to netcoreapp1.0, with xunit 2.2.0 and FakeItEasy 3.0.0

### PR DESCRIPTION
**Pull request by blairconrad**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)

### Description

Supports #2612 by converting tests to use xunit 2.0.0, and FakeItEasy 3.0.0 (where FakeItEasy is used). 

All test projects covering projects that build on netstandard have been added to the test run on Unix, except for `Nancy.Embedded.Tests`. No matter what I tried, the resolver returned from `EmbeddedStaticContentConventionBuilder.AddDirectory` returned `null` when invoked. Even when I replaced the return value of `AddDirectory` with a known non-`null` value.
I'm not sure if this is the same problem [described for the mono tests](https://github.com/NancyFx/Nancy/blob/master/build.cake#L306) or not, but I opted to convert everything else and submit the PR.

### CODE REVIEW

**Comment by thecodejunkie** [comment]
Awesome! We should make sure to tick them off here https://github.com/NancyFx/Nancy/issues/2612

**Comment by blairconrad** [comment]
@thecodejunkie, I don't have the ability.
I try clicking on the little boxes, but nothing happens. Perhaps only admins can do this?

**Comment by thecodejunkie** [comment]
@blairconrad maybe we can have a look at `Nancy.Embedded.Tests` once we've migrated over to the new project format and got rid of all the xproj / msbuild mess

**Comment by blairconrad** [comment]
@thecodejunkie, that sounds reasonable to me, a relatively disinterested outsider. :wink:

**Comment by blairconrad** [comment]
Thanks, for the merge, @horsdal.

**Comment by horsdal** [comment]
:+1:

**Pull request merged**
