### PR TITLE
Proposed fix for #1280

### PR DESCRIPTION
**Pull request by rasmus-beck**
This PR proposes a fix for #1280, and #1676.

It is not ready to be merged, as I need a few more tests. 

Input for tests are very welcome.

### CODE REVIEW

**Comment by thecodejunkie** [comment]
The OWIN v1 specification does mention encoding requirements for various environment keys
http://owin.org/spec/spec/owin-1.0.0.html#PercentEncoding

**Comment by rasmus-beck** [comment]
Hmmm... if I read this right, then we a decoded path when using OWIN. Well that kind of sucks doesn't it. We want the encoded path, so we can tell what forward slashes are path separators and which are not. Am I reading this right?

**Comment by grumpydev** [comment]
It does appear to be the opposite of what we want :/

**Comment by rasmus-beck** [comment]
What's the verdict then? What are we going to do?

**Comment by damianh** [comment]
Capturing a segment that has a  '/' encoded in it as a route param is never going to work. Not just on Nancy, but on _all_ webservers and web frameworks.

> Most web server implementations will perform percent-decoding on paths in order to perform request routing (as they rightly may, see: RFC 2616 section 5.1.2, also 3.2.3), and OWIN follows this precedent. 

http://owin.org/spec/spec/owin-1.0.0.html#PercentEncoding

> If the Request-URI is encoded using the "% HEX HEX" encoding [42], the origin server MUST decode the Request-URI in order to properly interpret the request.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1.2

> For example, the following three URIs are equivalent:

      http://abc.com:80/~smith/home.html
      http://ABC.com/%7Esmith/home.html
      http://ABC.com:/%7esmith/home.html

http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.2.3

This means Nancy will (should) never see a uri in the form http://host/foo%2Fbar/baz

If you want a `/` in a route param you will have to do a workarounds http://stackoverflow.com/a/26800648/1010

**Comment by damianh** [comment]
Given the above, #1676 this isn't fixable.

**Comment by grumpydev** [comment]
Yeah, having dug into the OWIN issue a bit more it looks like it is broken, but so is every other platform out there, which unfortunately means this isn't going to be fixable in a generic way (especially considering we are heading towards OWIN only hosting eventually) and should be "fixed" with education (don't put encoded slashes in paths).

**Comment by rasmus-beck** [comment]
I guess we might as well close this PR, and all related issues. I will see if I can write a paragraph on this for the wiki.

**Comment by damianh** [comment]
Yeah agree. Frustrating after all that effort. Of which, many thanks Rasmus.

**Comment by rasmus-beck** [comment]
Yes frustrating indeed, but that's how it goes sometimes. You have to get to that point where things just won't fit together to find out that it isn't possible.

**Comment by jchannon** [comment]
So this means we still have to have code likes this in projects?
```
var email = (string)parameters.email;
email = email.Replace(" ", "+");
```

**Comment by rasmus-beck** [comment]
Depends on what host you use. Do you use Asp.Net host, then you can still use the web.config work around, but you really shouldn't go down this route. I would suggest you do your own escaping in the urls you provide. So when you return a `/` escape it with something like `__s__`, or whatever you prefer.

The web.config work around is this (ref: http://danielwertheim.se/2014/10/11/uri-behaves-differently-in-net4-0-vs-net4-5/):
```xml
<configuration>
  <uri>
    <schemeSettings>
      <add name="http" genericUriParserOptions="DontUnescapePathDotsAndSlashes"/>
    </schemeSettings>
  </uri>
</configuration>
```

**Comment by jchannon** [comment]
Well this is incoming, so when you have a `/person/fred+1@home.com` the Nancy route parameter value will be decoded twice so have to put the + back in

**Comment by rasmus-beck** [comment]
Sorry... didn't actually look at your example @jchannon. 

I don't think that the fix proposed in this PR, or the web.config one, would do anything for you in that case. A plus is not a path character in windows. Dots and slashes are, and that's why they are treated differently, to prevent directory traversal / injection attacks.

If you try to double escape the query string you are just going to get a 404.11 status code back.

I can't remember where I got this list of characters from, but these seem to cause trouble for IIS `<>*%:&/\_`.

In your example the plus isn't even escaped once. You can't really expect that to work any other way than what you have explained. In a URL `+` means space, so you told it to put a space in there, not a plus sign. Whomever sent that request should at least try to escape once.

**Comment by jchannon** [comment]
Good point :+1:

**Comment by rbirkby** [comment]
To help others like me asking the same question, this PR does not cater for GMail Address Alias email addresses contained in path segments. For example:

    /a/b/c/test+account@gmail.com/d/e/f

Even though + is not a special character in URL paths, this PR [uses](https://github.com/NancyFx/Nancy/pull/1678/files#diff-1f270b3a7e4b130880a6d3535ebb232bR101) HttpUtility.UrlDecode() to decode each path segment. And UrlDecode will decode the + into a space character.

**Comment by rasmus-beck** [comment]
@rbirkby `+` is a special character in a URL. It means space. Look at this comment:
https://github.com/NancyFx/Nancy/pull/1678#issuecomment-71070613

**Comment by rbirkby** [comment]
@rasmus-beck The + is only special in a querystring. It is a valid character in the URL path (have a read of the spec).

Also:

```csharp
using System;
using System.Net;
					
public class Program
{
	public static void Main()
	{
		CheckValidity("http://a.b.com/address+alias@gmail.com/path");
		CheckValidity("http://a.b.com/address alias@gmail.com/path");
	}
	
	public static void CheckValidity(string url)
	{
		var uri = new Uri(url);
		Console.WriteLine("{0} ({1}): {2}", url, string.Join(", ", uri.Segments), Uri.IsWellFormedUriString(url, UriKind.Absolute));
	}
}
```

    http://a.b.com/address+alias@gmail.com/path (/, address+alias@gmail.com/, path): True
    http://a.b.com/address alias@gmail.com/path (/, address%20alias@gmail.com/, path): False

See how a space is encoded as %20, not as +, and how a + is not special in any way.

**Comment by rasmus-beck** [comment]
@rbirkby Ahhh good point. I really should learn to read. Anywho, closed the PR since it fails to follow multiple standards.

**Comment by taharrison** [comment]
@damianh, 
I think you've misinterpreted how %2f should behave.

from http://www.w3.org/Addressing/URL/uri-spec.html

> Example 2
> 
> The URIs
> 		http://www.w3.org/albert/bertram/marie-claude
>
> and
> 		http://www.w3.org/albert/bertram%2Fmarie-claude
>
> are NOT identical, as in the second case the encoded slash **does not have** hierarchical significance.

I believe that where you say: 
> the origin server MUST decode the Request-URI in order to properly interpret the request.

This isn't blind URL decoding.  It must first respect the url segments split by the unencoded "/"s, and then decode the segments.

Also, from http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.2.3 which you also quote:

> Characters **other than those** in the "reserved" and "unsafe" sets (see RFC 2396 [42]) are equivalent to their ""%" HEX HEX" encoding.

(added emphasis is mine.)  "/" is a character in reserved the reserved set.  It is not equivalent to "%2f"


shoutout to @rasmus-beck @khellang also.

**Comment by khellang** [comment]
I think @damianh's point was that *Nancy* will never see an encoded URI because the host will always decode it before it surfaces the request...

**Comment by khellang** [comment]
I just tested the following using `Microsoft.Owin.Host.HttpListener` and `Microsoft.Owin.Hosting`:

```csharp
public static class Program
{
    private const string Url = @"http://localhost:1337";

    public static void Main(string[] args)
    {
        using (WebApp.Start(Url, Configure))
        {
            Console.WriteLine("Listening at '{0}'...", Url);
            Console.ReadLine();
        }
    }

    private static void Configure(IAppBuilder app)
    {
        app.Run(ctx => ctx.Response.WriteAsync(ctx.Request.Uri.OriginalString));
    }
}
```

And the results:

 - `http://localhost:1337/albert/bertram%2Fmarie-claude` -> `http://localhost:1337/albert/bertram/marie-claude`
 - `http://localhost:1337/albert/bertram/marie-claude` -> `http://localhost:1337/albert/bertram/marie-claude`

As you can see, the `HttpListener` decodes the URI before passing it to the application, thus we will never know what the original URI was.

**Comment by grumpydev** [comment]
Yep, that's the problem, the attempted fix was to make sure nancy was responsible for decoding so we could create the segments correctly, but unfortunately it was out of our hands in several instances so there's not a whole lot we can do about it.

**Comment by khellang** [comment]
However, there *are* methods to get a hold of the raw URI, but it's far from host agnostic (which is kinda the point of OWIN).

If you change the `Configure` method above to

```csharp
private static void Configure(IAppBuilder app)
{
    app.Run(ctx =>
    {
        object context;
        if (ctx.Environment.TryGetValue("System.Net.HttpListenerContext", out context))
        {
            var httpListenerContext = context as HttpListenerContext;
            if (httpListenerContext != null)
            {
                return ctx.Response.WriteAsync(httpListenerContext.Request.RawUrl);
            }
        }

        return ctx.Response.WriteAsync(ctx.Request.Uri.OriginalString);
    });
}
```

The results are:

 - `http://localhost:1337/albert/bertram%2fmarie-claude` -> `/albert/bertram%2fmarie-claude`
 - `http://localhost:1337/albert/bertram/marie-claude` -> `/albert/bertram/marie-claude`

I'm pretty sure this is possible using System.Web and WCF (:mask:) as well. Maybe it's an idea to propose a `owin.RequestRawUrl` key for OWIN?

**Comment by damianh** [comment]
> Maybe it's an idea to propose a owin.RequestRawUrl key for OWIN?

@khellang something about that make me feel icky... think it'll just lead to confusion. May not be supportable in all hosts either i.e. SystemWeb.

**Comment by khellang** [comment]
@damianh System.Web has the same: http://referencesource.microsoft.com/#System.Web/Abstractions/HttpRequestBase.cs,c676f095dc09e1f5,references

**Comment by damianh** [comment]
ok, make it so then :p

**Pull request closed without merging**
